# =============================================================================
# Assignment 1: Build a Basic RAG Chatbot for a PDF Document
# Course      : Week 5 AI Class – RAG Assignments
# Institute   : Vidaamuyarchi Tech
# Submitted to: info@vidaamuyarchi.com
# =============================================================================

# ----------------------------- DEPENDENCIES ----------------------------------
# pip install langchain langchain-community faiss-cpu pypdf sentence-transformers
# pip install openai python-dotenv
# -----------------------------------------------------------------------------

import os
from dotenv import load_dotenv
from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain.chains import RetrievalQA
from langchain_community.llms import Ollama

load_dotenv()

# ========================== STEP 1: LOAD PDF ==================================
def load_pdf(pdf_path: str):
    """Load PDF and return documents."""
    print(f"[INFO] Loading PDF: {pdf_path}")
    loader = PyPDFLoader(pdf_path)
    documents = loader.load()
    print(f"[INFO] Loaded {len(documents)} pages from PDF.")
    return documents

# ======================== STEP 2: SPLIT INTO CHUNKS ===========================
def split_documents(documents, chunk_size=500, chunk_overlap=50):
    """Split documents into smaller chunks."""
    print("[INFO] Splitting documents into chunks...")
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )
    chunks = splitter.split_documents(documents)
    print(f"[INFO] Total chunks created: {len(chunks)}")
    return chunks

# ====================== STEP 3: GENERATE EMBEDDINGS ==========================
def create_vector_store(chunks):
    """Generate embeddings and store in FAISS vector database."""
    print("[INFO] Generating embeddings and creating FAISS vector store...")
    embedding_model = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )
    vector_store = FAISS.from_documents(chunks, embedding_model)
    print("[INFO] Vector store created successfully.")
    return vector_store

# ====================== STEP 4: BUILD RAG CHAIN ==============================
def build_rag_chain(vector_store):
    """Build a RetrievalQA chain using local LLM (Ollama)."""
    print("[INFO] Building RAG chain...")
    retriever = vector_store.as_retriever(search_kwargs={"k": 3})
    llm = Ollama(model="mistral")  # Change model as needed
    qa_chain = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=retriever,
        return_source_documents=True
    )
    print("[INFO] RAG chain ready.")
    return qa_chain

# ========================= STEP 5: CHATBOT LOOP ==============================
def run_chatbot(qa_chain):
    """Interactive chatbot loop."""
    print("\n" + "=" * 60)
    print("       RAG Chatbot – Ask Questions about your PDF       ")
    print("=" * 60)
    print("Type 'exit' to quit.\n")

    while True:
        user_query = input("You: ").strip()
        if user_query.lower() in ["exit", "quit"]:
            print("[INFO] Exiting chatbot. Goodbye!")
            break
        if not user_query:
            continue

        result = qa_chain.invoke({"query": user_query})
        answer = result["result"]
        sources = result.get("source_documents", [])

        print(f"\nBot: {answer}")
        if sources:
            print("\n[Sources]")
            for i, doc in enumerate(sources, 1):
                page = doc.metadata.get("page", "?")
                print(f"  {i}. Page {page + 1}: {doc.page_content[:100]}...")
        print()

# ================================ MAIN =======================================
if __name__ == "__main__":
    # ----- Sample Input -----
    PDF_PATH = "sample_document.pdf"   # Replace with your PDF file path

    if not os.path.exists(PDF_PATH):
        print(f"[ERROR] PDF file not found: {PDF_PATH}")
        print("[HINT] Place your PDF file in the same folder and update PDF_PATH.")
    else:
        documents  = load_pdf(PDF_PATH)
        chunks     = split_documents(documents)
        vector_db  = create_vector_store(chunks)
        qa_chain   = build_rag_chain(vector_db)
        run_chatbot(qa_chain)

# ========================= SAMPLE Q&A ========================================
# Q: What is the main topic of this document?
# A: (Based on the PDF content, the LLM will answer)
#
# Q: Summarize the key points.
# A: (Context retrieved from vector store, answer generated by LLM)
# =============================================================================
